// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenURL(arg1:string):Promise<void>;

export function Paint(arg1:main.RequestData):Promise<main.ResponseData>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadSettings():Promise<any>;

export function Request(arg1:main.RequestData):Promise<main.ResponseData>;

export function SelectFile(arg1:Array<main.FileFilter>):Promise<string>;

export function WriteSettings(arg1:string):Promise<void>;
